name: Build and Validate

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-console:
    name: Build Console Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      working-directory: ./PublicApiTableViewer-Project/PublicApiTableViewer
      run: dotnet restore
      
    - name: Build application
      working-directory: ./PublicApiTableViewer-Project/PublicApiTableViewer
      run: dotnet build --no-restore --configuration Release
      
    - name: Validate project structure
      working-directory: ./PublicApiTableViewer-Project/PublicApiTableViewer
      run: |
        echo "Validating project structure..."
        required_dirs=("Models" "Services" "Utilities")
        required_files=("Program.cs" "PublicApiTableViewer.csproj" "README.md" ".gitignore")
        
        for dir in "${required_dirs[@]}"; do
          if [ ! -d "$dir" ]; then
            echo "❌ Required directory $dir not found"
            exit 1
          fi
        done
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Required file $file not found"
            exit 1
          fi
        done
        echo "✅ Project structure validation passed"
        
    - name: Check code formatting
      working-directory: ./PublicApiTableViewer-Project/PublicApiTableViewer
      run: dotnet format --verify-no-changes --verbosity diagnostic || true

  validate-web:
    name: Validate Web Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate web application structure
      working-directory: ./PublicApiTableViewer-Project/PublicApiTableViewer.Web
      run: |
        echo "Validating web application structure..."
        required_files=("index.html" "app.js" "styles.css" "README.md")
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Required file $file not found"
            exit 1
          fi
        done
        
        # Validate HTML structure
        if ! grep -q "PUBLIC API TABLE VIEWER" index.html; then
          echo "❌ HTML structure validation failed"
          exit 1
        fi
        
        # Validate JavaScript file
        if [ ! -s app.js ]; then
          echo "❌ app.js is empty or missing"
          exit 1
        fi
        
        echo "✅ Web application validation passed"

  validate-documentation:
    name: Validate Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check documentation files
      run: |
        echo "Validating documentation..."
        required_files=("PublicApiTableViewer-Project/README.md" "PublicApiTableViewer-Project/PublicApiTableViewer/README.md" "PublicApiTableViewer-Project/PublicApiTableViewer.Web/README.md")
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Required documentation $file not found"
            exit 1
          fi
          if [ ! -s "$file" ]; then
            echo "❌ Documentation file $file is empty"
            exit 1
          fi
        done
        echo "✅ All documentation files present"

