name: Build and Validate

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      working-directory: ./PublicApiTableViewer-Project/PublicApiTableViewer
      run: dotnet restore
      
    - name: Build application
      working-directory: ./PublicApiTableViewer-Project/PublicApiTableViewer
      run: dotnet build --no-restore --configuration Release
      
    - name: Run application (basic validation)
      working-directory: ./PublicApiTableViewer-Project/PublicApiTableViewer
      run: |
        echo "Running application for basic validation..."
        timeout 10s dotnet run --no-build --configuration Release || true
        
    - name: Check code formatting
      working-directory: ./PublicApiTableViewer-Project/PublicApiTableViewer
      run: |
        echo "Checking code formatting..."
        dotnet format --verify-no-changes --verbosity diagnostic
        
    - name: Validate project structure
      working-directory: ./PublicApiTableViewer-Project/PublicApiTableViewer
      run: |
        echo "Validating project structure..."
        if [ ! -f "Program.cs" ]; then
          echo "❌ Program.cs not found"
          exit 1
        fi
        if [ ! -d "Models" ]; then
          echo "❌ Models directory not found"
          exit 1
        fi
        if [ ! -d "Services" ]; then
          echo "❌ Services directory not found"
          exit 1
        fi
        if [ ! -d "Utilities" ]; then
          echo "❌ Utilities directory not found"
          exit 1
        fi
        echo "✅ Project structure validation passed"
        
    - name: Check for required files
      working-directory: ./PublicApiTableViewer-Project/PublicApiTableViewer
      run: |
        echo "Checking for required files..."
        required_files=("README.md" ".gitignore" "PublicApiTableViewer.csproj" ".editorconfig")
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Required file $file not found"
            exit 1
          fi
        done
        echo "✅ All required files present"
        
    - name: Build success notification
      run: |
        echo "🎉 Build completed successfully!"
        echo "✅ Dependencies restored"
        echo "✅ Application built"
        echo "✅ Code formatting validated"
        echo "✅ Project structure validated"
        echo "✅ Required files present"
        echo "✅ Code quality checks passed"
